### ISSUE TITLE
Vault Master Task

### ISSUE THREAD

**Issue by paolopaolopaolo** [yeti/yurt#43]
Enable Yurt to add vault credentials/IP Addresses, and utilize a vault for secrets keeping

Things to Do:
- [x] #44 Add a method to fab called `add.vault`
- [x] #45 Add a flag/flow on `add.remote_server` that tells Yurt to create config files that generates/looks up vault secrets rather than generates/sets hardcoded-secrets
- [x] #46 Add lookup engine to project-wide Ansible Configs

 ~~Figure out how to implement vault for `git_pub_key` and `git_priv_key`, which are defined in base.yml and not on env files~~ (moved to issue #47 )
