### ISSUE TITLE
Add Provisioning/Orchestration functionality Epic

### ISSUE THREAD

**Issue by paolopaolopaolo** [yeti/yurt#80]
This epic will cover features that enable users to more easily handle the Ansible config side of things.
- [ ] Enable user to manage the `site.yml` file (add or remove provisioning groups that are run on deploy) (#82)
- [ ] Enable user to manage provisioning groups like `appservers.yml` or `dbservers.yml` (add or remove roles) (#81)
- [ ] Enable user to manage roles (can create the template for new roles) (#73)
